### ISSUE TITLE
Crashed on Swagger Petstore example

### ISSUE THREAD

**Issue by zamotivator** [lonelycode/tyk#116]
I seted up latest tyk (1.8.3.2) + tyk dashboard (0.9.6.5) and tried to import Swagger Petstore example:
https://raw.githubusercontent.com/swagger-api/swagger-spec/master/examples/v2.0/json/petstore.json

As result, tyk crashed

```
vagrant@precise64:~$ tyk
INFO[0000] Creating new Redis connection pool
INFO[0000] Setting up Server
WARN[0000] --> Standard listener (http)
INFO[0000] Detected 0 APIs
INFO[0000] Gateway started (v1.8.3.2)
INFO[0000] --> Listening on port: 5000
INFO[0469] Reload signal received, reloading endpoints
INFO[0469] Detected 1 APIs
INFO[0469] --> Loading API: Swagger Petstore
panic: http: invalid pattern

goroutine 7 [running]:
net/http.(*ServeMux).Handle(0xc8201928a0, 0x0, 0x0, 0x7ff20ff9cfe0, 0xc8203f2c40)
	/usr/local/go/src/net/http/server.go:1709 +0x127
main.loadApps(0xc8201ae800, 0x1, 0x1, 0xc8201928a0)
	/home/tyk/go/src/github.com/lonelycode/tyk/main.go:497 +0x1f94
main.ReloadURLStructure()
	/home/tyk/go/src/github.com/lonelycode/tyk/main.go:597 +0x12a
main.HandleRedisReloadMsg(0xc8204d31a0, 0x19, 0xc8203620f0, 0x45, 0x45)
	/home/tyk/go/src/github.com/lonelycode/tyk/reload_signal.go:39 +0x2df
main.(*RedisClusterStorageManager).StartPubSubHandler(0xc8202d9f48, 0xce2040, 0x19, 0xe109a0, 0x0, 0x0)
	/home/tyk/go/src/github.com/lonelycode/tyk/redis_cluster_handler.go:440 +0x48f
main.StartPubSubLoop()
	/home/tyk/go/src/github.com/lonelycode/tyk/reload_signal.go:18 +0x8f
created by main.main
	/home/tyk/go/src/github.com/lonelycode/tyk/main.go:758 +0x4cf

goroutine 1 [chan receive, 7 minutes]:
github.com/rcrowley/goagain.Wait(0x7ff20ff9d0a8, 0xc8200285a0, 0x7ff20ff9d0a8, 0x0, 0x0)
	/home/tyk/go/src/github.com/rcrowley/goagain/goagain.go:207 +0x41a
main.main()
	/home/tyk/go/src/github.com/lonelycode/tyk/main.go:863 +0x11ab

goroutine 17 [syscall, 7 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall, 7 minutes]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 18 [sleep, 1 minutes]:
time.Sleep(0x2540be400)
	/usr/local/go/src/runtime/time.go:59 +0xf9
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:199 +0x28
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.MongoPurger.StartPurgeLoop(0xc820284020, 0xc8204cd600, 0xa)
	/home/tyk/go/src/github.com/lonelycode/tyk/analytics.go:201 +0x58
main.(*MongoPurger).StartPurgeLoop(0xc82027e3a0, 0xa)
	<autogenerated>:7 +0xa2
created by main.setupGlobals
	/home/tyk/go/src/github.com/lonelycode/tyk/main.go:90 +0x4a3

goroutine 8 [select, 1 minutes]:
labix.org/v2/mgo.(*mongoCluster).syncServersLoop(0xc820185590)
	/home/tyk/go/src/labix.org/v2/mgo/cluster.go:368 +0x61f
created by labix.org/v2/mgo.newCluster
	/home/tyk/go/src/labix.org/v2/mgo/cluster.go:72 +0x1a0

goroutine 10 [IO wait, 7 minutes]:
net.runtime_pollWait(0x7ff20ff97b98, 0x72, 0xc82000a240)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82026d2c0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82026d2c0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82026d260, 0xc82050aa20, 0x24, 0x24, 0x0, 0x7ff20ff8e050, 0xc82000a240)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8200285b0, 0xc82050aa20, 0x24, 0x24, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
labix.org/v2/mgo.fill(0x7ff20ff96d48, 0xc8200285b0, 0xc82050aa20, 0x24, 0x24, 0x0, 0x0)
	/home/tyk/go/src/labix.org/v2/mgo/socket.go:489 +0x6c
labix.org/v2/mgo.(*mongoSocket).readLoop(0xc82007a540)
	/home/tyk/go/src/labix.org/v2/mgo/socket.go:506 +0x132
created by labix.org/v2/mgo.newSocket
	/home/tyk/go/src/labix.org/v2/mgo/socket.go:163 +0x402

goroutine 23 [sleep, 1 minutes]:
time.Sleep(0x12a05f200)
	/usr/local/go/src/runtime/time.go:59 +0xf9
labix.org/v2/mgo.(*mongoServer).pinger(0xc82007a460, 0x1)
	/home/tyk/go/src/labix.org/v2/mgo/server.go:284 +0x1a7
created by labix.org/v2/mgo.newServer
	/home/tyk/go/src/labix.org/v2/mgo/server.go:87 +0x162

goroutine 24 [IO wait, 7 minutes]:
net.runtime_pollWait(0x7ff20ff97c58, 0x72, 0xc82000a240)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82026d1e0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82026d1e0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc82026d180, 0x0, 0x7ff20e7523d0, 0xc8204e68c0)
	/usr/local/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc8200285a0, 0x4fd780, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc8200285a0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
net/http.(*Server).Serve(0xc8204d6780, 0x7ff20ff9d0a8, 0xc8200285a0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1887 +0xb3
net/http.Serve(0x7ff20ff9d0a8, 0xc8200285a0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1765 +0x85
created by main.main
	/home/tyk/go/src/github.com/lonelycode/tyk/main.go:825 +0x15bc

goroutine 25 [select, 7 minutes, locked to thread]:
runtime.gopark(0xe11058, 0xc820026f28, 0xc40918, 0x6, 0x18, 0x2)
	/usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc820026f28, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc820026f28)
	/usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 26 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7ff20ff97ad8, 0x72, 0xc82000a240)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82016c3e0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82016c3e0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82016c380, 0xc820505500, 0x24, 0x24, 0x0, 0x7ff20ff8e050, 0xc82000a240)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8202a8018, 0xc820505500, 0x24, 0x24, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
labix.org/v2/mgo.fill(0x7ff20ff96d48, 0xc8202a8018, 0xc820505500, 0x24, 0x24, 0x0, 0x0)
	/home/tyk/go/src/labix.org/v2/mgo/socket.go:489 +0x6c
labix.org/v2/mgo.(*mongoSocket).readLoop(0xc8202b2380)
	/home/tyk/go/src/labix.org/v2/mgo/socket.go:506 +0x132
created by labix.org/v2/mgo.newSocket
	/home/tyk/go/src/labix.org/v2/mgo/socket.go:163 +0x402

goroutine 27 [select, 1 minutes]:
labix.org/v2/mgo.(*mongoCluster).syncServersLoop(0xc8200b61e0)
	/home/tyk/go/src/labix.org/v2/mgo/cluster.go:368 +0x61f
created by labix.org/v2/mgo.newCluster
	/home/tyk/go/src/labix.org/v2/mgo/cluster.go:72 +0x1a0

goroutine 29 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7ff20ff97a18, 0x72, 0xc82000a240)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82016c5a0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82016c5a0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82016c540, 0xc8204e41e0, 0x24, 0x24, 0x0, 0x7ff20ff8e050, 0xc82000a240)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8202a8030, 0xc8204e41e0, 0x24, 0x24, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
labix.org/v2/mgo.fill(0x7ff20ff96d48, 0xc8202a8030, 0xc8204e41e0, 0x24, 0x24, 0x0, 0x0)
	/home/tyk/go/src/labix.org/v2/mgo/socket.go:489 +0x6c
labix.org/v2/mgo.(*mongoSocket).readLoop(0xc8202b2620)
	/home/tyk/go/src/labix.org/v2/mgo/socket.go:506 +0x132
created by labix.org/v2/mgo.newSocket
	/home/tyk/go/src/labix.org/v2/mgo/socket.go:163 +0x402

goroutine 30 [sleep, 1 minutes]:
time.Sleep(0x12a05f200)
	/usr/local/go/src/runtime/time.go:59 +0xf9
labix.org/v2/mgo.(*mongoServer).pinger(0xc8202b2540, 0x1)
	/home/tyk/go/src/labix.org/v2/mgo/server.go:284 +0x1a7
created by labix.org/v2/mgo.newServer
	/home/tyk/go/src/labix.org/v2/mgo/server.go:87 +0x162

goroutine 55 [sleep, 1 minutes]:
time.Sleep(0x1dcd6500)
	/usr/local/go/src/runtime/time.go:59 +0xf9
labix.org/v2/mgo.(*mongoCluster).syncServersLoop(0xc8200b63c0)
	/home/tyk/go/src/labix.org/v2/mgo/cluster.go:342 +0x2b1
created by labix.org/v2/mgo.newCluster
	/home/tyk/go/src/labix.org/v2/mgo/cluster.go:72 +0x1a0

goroutine 57 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7ff20ff97898, 0x72, 0xc82000a240)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82010a450, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82010a450, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82010a3f0, 0xc8204ee720, 0x24, 0x24, 0x0, 0x7ff20ff8e050, 0xc82000a240)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8202a88d8, 0xc8204ee720, 0x24, 0x24, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
labix.org/v2/mgo.fill(0x7ff20ff96d48, 0xc8202a88d8, 0xc8204ee720, 0x24, 0x24, 0x0, 0x0)
	/home/tyk/go/src/labix.org/v2/mgo/socket.go:489 +0x6c
labix.org/v2/mgo.(*mongoSocket).readLoop(0xc8202b27e0)
	/home/tyk/go/src/labix.org/v2/mgo/socket.go:506 +0x132
created by labix.org/v2/mgo.newSocket
	/home/tyk/go/src/labix.org/v2/mgo/socket.go:163 +0x402

goroutine 58 [sleep, 1 minutes]:
time.Sleep(0x12a05f200)
	/usr/local/go/src/runtime/time.go:59 +0xf9
labix.org/v2/mgo.(*mongoServer).pinger(0xc8202b2700, 0x1)
	/home/tyk/go/src/labix.org/v2/mgo/server.go:284 +0x1a7
created by labix.org/v2/mgo.newServer
	/home/tyk/go/src/labix.org/v2/mgo/server.go:87 +0x162
```

**Comment by lonelycode** [comment]
In the dashboard, fill in the listen-path value. That should solve it

**Comment by zamotivator** [comment]
Good workaround, but it's obviously bug and should be fixed (otherwise server can be crashed by some user input)

**Comment by lonelycode** [comment]
Never said it wouldn't be fixed.
Putting a workaround in our issue tracker will help others until the fix is released.

**Comment by zamotivator** [comment]
Oh, thank you very much, now I got your point.

**Comment by lonelycode** [comment]
Fixed in Develop - Tyk will skip over invalid listen_paths now.
